### ISSUE TITLE
False claim of open source

### ISSUE THREAD

**Issue by Cohejh** [meforce/HollaPRO#1]
This browser claims to open source, in https://github.com/meforce/HollaPRO#how-do-i-know-holla-doesnt-take-telemetry , it says "Holla is built around on open source technologies and therefore we love transparency. You're welcome to perform your own audits on our entirely open source code! " The code is locked away behind a paywall. Either remove this claim or make it open source

**Comment by meforce** [comment]
The project has open source code. It is not available as open source. You have to buy the upgrades.

**Comment by Cohejh** [comment]
Please then remove the **"entirely"** open source code. It is evidently not entirely open source.

**Comment by snaildos** [comment]
> The project has open source code. It is not available as open source. You have to buy the upgrades.

Of course you love open source, you thiefs. Remove the project now and issue all refunds to everyone who has bought it.
